default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: eltask_development

test:
  <<: *default
  database: eltask_test

production:
  <<: *default
  database: <%= ENV['ELTASK_DATABASE_NAME'] %>
  username: <%= ENV['ELTASK_DATABASE_USERNAME'] %>
  password: <%= ENV['ELTASK_DATABASE_PASSWORD'] %>
  host: <%= ENV['ELTASK_DATABASE_HOST'] %>
